import type { Wine } from "./types";

// ---------------------------------------------------------------------------
// SEED DATA — the mock cellar.
// Each object matches the `Wine` type in ./types. It's a plain local array so
// the app runs with zero backend. To move to a real source (e.g. WordPress)
// later, keep the function signatures in ./wines unchanged and replace their
// bodies with `fetch()` calls — the components that consume them won't change.
// ---------------------------------------------------------------------------
export const SEED: Wine[] = [
  // ---------- France · Bordeaux ----------
  {
    id: "fr-margaux-2015",
    name: "Grand Vin du Château Margaux",
    producer: "Château Margaux",
    type: "red",
    grapeVariety: ["Cabernet Sauvignon", "Merlot", "Cabernet Franc", "Petit Verdot"],
    year: 2015,
    quantity: 2,
    description:
      "First-growth Bordeaux since 1855 and the purest expression of the estate — finesse, elegance and power in rare harmony.",
    score: 98,
    appellation: "Margaux",
    price: 850,
    alcoholicStrength: 13.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Bordeaux",
    address: "33460 Margaux, France",
    tastingNotes:
      "Violets, cassis and cedar; silky tannins with remarkable acidity and a very long finish.",
    readyToDrink: true,
  },
  {
    id: "fr-pavillonrouge-2018",
    name: "Pavillon Rouge du Château Margaux",
    producer: "Château Margaux",
    type: "red",
    grapeVariety: ["Cabernet Sauvignon", "Merlot", "Petit Verdot"],
    year: 2018,
    quantity: 3,
    description:
      "The estate's historic second wine — the oldest second wine in the Médoc, bearing its name since the 1906 vintage.",
    score: 93,
    appellation: "Margaux",
    price: 190,
    alcoholicStrength: 13.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Bordeaux",
    address: "33460 Margaux, France",
    tastingNotes:
      "Blackcurrant, graphite and rose petal; fine structure faithful to the identity of Château Margaux.",
    readyToDrink: true,
  },
  {
    id: "fr-margauxtroisieme-2019",
    name: "Margaux du Château Margaux",
    producer: "Château Margaux",
    type: "red",
    grapeVariety: ["Cabernet Sauvignon", "Merlot"],
    year: 2019,
    quantity: 4,
    description:
      "The estate's third wine — an early-drinking introduction to the perfumed charm of the Margaux terroir.",
    score: 89,
    appellation: "Margaux",
    price: 75,
    alcoholicStrength: 13.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Bordeaux",
    address: "33460 Margaux, France",
    tastingNotes: "Red cherry, violet and sweet spice; supple, elegant and charming.",
    readyToDrink: true,
  },
  {
    id: "fr-pavillonblanc-2020",
    name: "Pavillon Blanc du Château Margaux",
    producer: "Château Margaux",
    type: "white",
    grapeVariety: ["Sauvignon Blanc"],
    year: 2020,
    quantity: 3,
    description:
      "100% Sauvignon Blanc of purity and precision, aged around eight months with roughly 20% new French oak.",
    score: 94,
    appellation: "Bordeaux Blanc",
    price: 95,
    alcoholicStrength: 13.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Bordeaux",
    address: "33460 Margaux, France",
    tastingNotes:
      "Lime blossom, gooseberry and flint; layered, aromatic and remarkably age-worthy.",
    readyToDrink: true,
  },
  {
    id: "fr-lafite-2010",
    name: "Château Lafite Rothschild",
    producer: "Château Lafite Rothschild",
    type: "red",
    grapeVariety: ["Cabernet Sauvignon", "Merlot", "Petit Verdot"],
    year: 2010,
    quantity: 1,
    description:
      "First-growth Pauillac from a legendary vintage — aristocratic Lafite at its most profound.",
    score: 99,
    appellation: "Pauillac",
    price: 1000,
    alcoholicStrength: 13.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Bordeaux",
    address: "33250 Pauillac, France",
    tastingNotes:
      "Cedar, pencil shavings, blackcurrant and graphite; weightless depth with decades ahead.",
    readyToDrink: false,
  },
  {
    id: "fr-carruades-2015",
    name: "Carruades de Lafite",
    producer: "Château Lafite Rothschild",
    type: "red",
    grapeVariety: ["Cabernet Sauvignon", "Merlot", "Petit Verdot"],
    year: 2015,
    quantity: 2,
    description:
      "The second wine of Lafite, from plots adjacent to the Grand Vin's famous Carruades plateau.",
    score: 92,
    appellation: "Pauillac",
    price: 220,
    alcoholicStrength: 13.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Bordeaux",
    address: "33250 Pauillac, France",
    tastingNotes: "Cassis, cedar and violet; refined tannins with classic Lafite perfume.",
    readyToDrink: true,
  },

  // ---------- Champagne & Sparkling ----------
  {
    id: "fr-domperignon-2012",
    name: "Dom Pérignon",
    producer: "Moët & Chandon",
    type: "sparkling",
    grapeVariety: ["Chardonnay", "Pinot Noir"],
    year: 2012,
    quantity: 4,
    description:
      "Prestige vintage Champagne made only in exceptional years — 2012 incarnates its essence with rare intensity.",
    score: 96,
    appellation: "Champagne",
    price: 185,
    alcoholicStrength: 12.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Champagne",
    address: "51200 Épernay, France",
    tastingNotes:
      "Pastry, hint of smoke, lime and tangerine; tense, vibrant and destined for a second life as P2.",
    readyToDrink: true,
  },
  {
    id: "fr-domperignon-2013",
    name: "Dom Pérignon",
    producer: "Moët & Chandon",
    type: "sparkling",
    grapeVariety: ["Chardonnay", "Pinot Noir"],
    year: 2013,
    quantity: 3,
    description:
      "A late-ripening, cool vintage — Dom Pérignon 2013 is taut and chiselled with superb freshness.",
    score: 95,
    appellation: "Champagne",
    price: 210,
    alcoholicStrength: 12.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Champagne",
    address: "51200 Épernay, France",
    tastingNotes: "White peach, iodine and toasted almond; racy acidity, chalky drive.",
    readyToDrink: true,
  },
  {
    id: "fr-domperignon-2015",
    name: "Dom Pérignon",
    producer: "Moët & Chandon",
    type: "sparkling",
    grapeVariety: ["Chardonnay", "Pinot Noir"],
    year: 2015,
    quantity: 2,
    description:
      "A warm, generous vintage rendered luminous — opulent yet precise, released in the Murakami-designed edition.",
    score: 95,
    appellation: "Champagne",
    price: 230,
    alcoholicStrength: 12.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Champagne",
    address: "51200 Épernay, France",
    tastingNotes: "Ripe pear, brioche and candied citrus; creamy mousse, long and glowing.",
    readyToDrink: false,
  },
  {
    id: "fr-domperignon-2017",
    name: "Dom Pérignon",
    producer: "Moët & Chandon",
    type: "sparkling",
    grapeVariety: ["Chardonnay", "Pinot Noir"],
    year: 2017,
    quantity: 2,
    description:
      "An early, sun-soaked harvest giving an unusually charming, aromatic young Dom Pérignon.",
    score: 94,
    appellation: "Champagne",
    price: 270,
    alcoholicStrength: 12.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Champagne",
    address: "51200 Épernay, France",
    tastingNotes: "Mirabelle, acacia honey and fresh almond; open-knit yet finely built.",
    readyToDrink: true,
  },
  {
    id: "fr-krug-grandecuvee-nv",
    name: "Grande Cuvée 172ème Édition",
    producer: "Krug",
    type: "sparkling",
    grapeVariety: ["Chardonnay", "Pinot Noir", "Pinot Meunier"],
    year: 2016,
    quantity: 3,
    description:
      "The reference multi-vintage Champagne — 172ème edition, built around the 2016 harvest from 146 wines.",
    score: 95,
    appellation: "Champagne",
    price: 220,
    alcoholicStrength: 13.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Champagne",
    address: "5 Rue Coquebert, 51100 Reims, France",
    tastingNotes:
      "Flowers in bloom, ripe citrus, marzipan and gingerbread; hazelnut and nougat on a powerful palate.",
    readyToDrink: true,
  },
  {
    id: "fr-bollinger-lga-2014",
    name: "La Grande Année",
    producer: "Bollinger",
    type: "sparkling",
    grapeVariety: ["Pinot Noir", "Chardonnay"],
    year: 2014,
    quantity: 3,
    description:
      "Vintage Champagne fermented entirely in old magnums — barrel-fermented richness with Ay power.",
    score: 94,
    appellation: "Champagne",
    price: 120,
    alcoholicStrength: 12.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Champagne",
    address: "51160 Aÿ, France",
    tastingNotes: "Stewed quince, walnut and brioche; broad, vinous and deeply savoury.",
    readyToDrink: true,
  },
  {
    id: "gb-nyetimber-bdb-2017",
    name: "Blanc de Blancs",
    producer: "Nyetimber",
    type: "sparkling",
    grapeVariety: ["Chardonnay"],
    year: 2017,
    quantity: 6,
    description:
      "England's benchmark sparkling house — pure Chardonnay from Sussex's greensand and chalk soils.",
    score: 93,
    appellation: "Sussex",
    price: 45,
    alcoholicStrength: 12.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "England",
    region: "West Sussex",
    address: "West Chiltington, Pulborough RH20 2JW, England",
    tastingNotes:
      "Lemon, baked apple, jasmine and vanilla; soft mousse with a long, buttery, toasty finish.",
    readyToDrink: true,
  },
  {
    id: "gb-nyetimber-1086-2013",
    name: "1086 Prestige Cuvée",
    producer: "Nyetimber",
    type: "sparkling",
    grapeVariety: ["Chardonnay", "Pinot Noir"],
    year: 2013,
    quantity: 1,
    description:
      "Nyetimber's prestige cuvée, named for the Domesday Book entry of its estate — England's answer to grand marque icons.",
    score: 95,
    appellation: "Sussex",
    price: 150,
    alcoholicStrength: 12.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "England",
    region: "West Sussex",
    address: "West Chiltington, Pulborough RH20 2JW, England",
    tastingNotes: "Toast, orchard fruit and hazelnut; profound, creamy and persistent.",
    readyToDrink: true,
  },

  // ---------- France · Burgundy ----------
  {
    id: "fr-leflaive-chevalier-2016",
    name: "Chevalier-Montrachet Grand Cru",
    producer: "Domaine Leflaive",
    type: "white",
    grapeVariety: ["Chardonnay"],
    year: 2016,
    quantity: 1,
    description:
      "Grand cru white Burgundy from Puligny's greatest family — biodynamic farming since the 1990s.",
    score: 96,
    appellation: "Chevalier-Montrachet Grand Cru",
    price: 350,
    alcoholicStrength: 13.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Burgundy",
    address: "21190 Puligny-Montrachet, France",
    tastingNotes: "White flowers, crushed stone and hazelnut; immense tension and length.",
    readyToDrink: false,
  },
  {
    id: "fr-leflaive-pucelles-2013",
    name: "Puligny-Montrachet Les Pucelles 1er Cru",
    producer: "Domaine Leflaive",
    type: "white",
    grapeVariety: ["Chardonnay"],
    year: 2013,
    quantity: 2,
    description:
      "One of Puligny's most celebrated premier crus — lacy, mineral Chardonnay of great refinement.",
    score: 94,
    appellation: "Puligny-Montrachet 1er Cru",
    price: 200,
    alcoholicStrength: 13.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Burgundy",
    address: "21190 Puligny-Montrachet, France",
    tastingNotes: "Acacia, lemon curd and oyster shell; silky, saline and precise.",
    readyToDrink: true,
  },
  {
    id: "fr-drc-2018",
    name: "Romanée-Conti",
    producer: "Domaine de la Romanée-Conti",
    type: "red",
    grapeVariety: ["Pinot Noir"],
    year: 2018,
    quantity: 1,
    description:
      "The benchmark Burgundian Pinot Noir — impossibly fine and rare.",
    score: 99,
    appellation: "Romanée-Conti Grand Cru",
    price: 2500,
    alcoholicStrength: 13.8,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Burgundy",
    address: "21700 Vosne-Romanée, France",
    tastingNotes:
      "Rose petal, red cherry and spice; ethereal, weightless yet profound.",
    readyToDrink: false,
  },

  // ---------- Germany ----------
  {
    id: "de-egonmuller-kabinett-2016",
    name: "Scharzhofberger Riesling Kabinett",
    producer: "Egon Müller",
    type: "white",
    grapeVariety: ["Riesling"],
    year: 2016,
    quantity: 3,
    description:
      "From Germany's most hallowed vineyard — feather-light, off-dry Riesling of legendary delicacy.",
    score: 95,
    appellation: "Mosel",
    price: 95,
    alcoholicStrength: 8.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Germany",
    region: "Mosel",
    address: "54459 Wiltingen/Scharzhof, Germany",
    tastingNotes: "White peach, elderflower and slate; weightless sweetness, electric acid.",
    readyToDrink: true,
  },
  {
    id: "de-jjprum-auslese-2009",
    name: "Wehlener Sonnenuhr Riesling Auslese",
    producer: "Joh. Jos. Prüm",
    type: "white",
    grapeVariety: ["Riesling"],
    year: 2009,
    quantity: 4,
    description:
      "Classic blue-slate Auslese from an estate synonymous with long-aged Mosel Riesling.",
    score: 94,
    appellation: "Mosel",
    price: 60,
    alcoholicStrength: 8.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Germany",
    region: "Mosel",
    address: "54472 Bernkastel-Wehlen, Germany",
    tastingNotes: "Apricot, honey and lime leaf; luscious yet racy with smoky minerality.",
    readyToDrink: true,
  },
  {
    id: "de-donnhoff-spatlese-2007",
    name: "Niederhäuser Hermannshöhle Riesling Spätlese",
    producer: "Dönnhoff",
    type: "white",
    grapeVariety: ["Riesling"],
    year: 2007,
    quantity: 4,
    description:
      "Spätlese from the Nahe's greatest vineyard — now beautifully mature with a long road ahead.",
    score: 94,
    appellation: "Nahe",
    price: 55,
    alcoholicStrength: 8.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Germany",
    region: "Nahe",
    address: "55585 Oberhausen an der Nahe, Germany",
    tastingNotes: "Honeyed apricot, mango and wet stone; sweet fruit carried by laser acidity.",
    readyToDrink: true,
  },
  {
    id: "de-keller-abtserde-2016",
    name: "Westhofener Brunnenhäuschen Abtserde GG",
    producer: "Keller",
    type: "white",
    grapeVariety: ["Riesling"],
    year: 2016,
    quantity: 2,
    description:
      "Grosses Gewächs from limestone-rich Abtserde — arguably Germany's finest dry-Riesling site.",
    score: 96,
    appellation: "Rheinhessen",
    price: 90,
    alcoholicStrength: 12.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Germany",
    region: "Rheinhessen",
    address: "67593 Westhofen, Germany",
    tastingNotes: "Pineapple, herbs and crushed limestone; immense density, bone dry.",
    readyToDrink: true,
  },
  {
    id: "de-gmax-2019",
    name: "G-Max Riesling Trocken",
    producer: "Keller",
    type: "white",
    grapeVariety: ["Riesling"],
    year: 2019,
    quantity: 1,
    description:
      "Cult dry Riesling from the Rheinhessen — tiny and prized, sealed with wax like Grandfather Max did.",
    score: 96,
    appellation: "Rheinhessen",
    price: 60,
    alcoholicStrength: 12.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Germany",
    region: "Rheinhessen",
    address: "67593 Westhofen, Germany",
    tastingNotes: "Lime, white peach and crushed stone; laser-precise.",
    readyToDrink: true,
  },

  // ---------- Austria ----------
  {
    id: "at-brundlmayer-lamm-2023",
    name: "Ried Lamm Grüner Veltliner 1ÖTW",
    producer: "Weingut Bründlmayer",
    type: "white",
    grapeVariety: ["Grüner Veltliner"],
    year: 2023,
    quantity: 3,
    description:
      "Erste Lage Grüner Veltliner from Kamptal's warmest site, fermented in old Austrian oak and acacia.",
    score: 94,
    appellation: "Kamptal DAC",
    price: 55,
    alcoholicStrength: 13.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Austria",
    region: "Lower Austria",
    address: "Zwettlerstraße 23, 3550 Langenlois, Austria",
    tastingNotes: "Yellow plum, white pepper and tobacco; dense yet elegant, long and spicy.",
    readyToDrink: true,
  },
  {
    id: "at-brundlmayer-heiligenstein-2024",
    name: "Ried Heiligenstein Riesling 1ÖTW",
    producer: "Weingut Bründlmayer",
    type: "white",
    grapeVariety: ["Riesling"],
    year: 2024,
    quantity: 3,
    description:
      "Riesling from Austria's most storied vineyard — 270-million-year-old desert sandstone above the Danube.",
    score: 93,
    appellation: "Kamptal DAC",
    price: 50,
    alcoholicStrength: 13.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Austria",
    region: "Lower Austria",
    address: "Zwettlerstraße 23, 3550 Langenlois, Austria",
    tastingNotes: "Apricot, quince and stone dust; taut, mineral and cool-hearted.",
    readyToDrink: true,
  },
  {
    id: "at-moric-alterebeben-2017",
    name: "Blaufränkisch Alte Reben",
    producer: "Moric",
    type: "red",
    grapeVariety: ["Blaufränkisch"],
    year: 2017,
    quantity: 4,
    description:
      "Roland Velich's old-vine Blaufränkisch — Burgenland's answer to fine Burgundy, all limestone lift.",
    score: 93,
    appellation: "Burgenland",
    price: 45,
    alcoholicStrength: 12.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Austria",
    region: "Burgenland",
    address: "Kirchengasse 3, 7051 Großhöflein, Austria",
    tastingNotes: "Dark cherry, slate and violets; sinewy, cool-toned and endlessly fine.",
    readyToDrink: true,
  },

  // ---------- Rosé ----------
  {
    id: "fr-esclans-garrus-2021",
    name: "Garrus",
    producer: "Château d'Esclans",
    type: "rosé",
    grapeVariety: ["Grenache", "Rolle"],
    year: 2021,
    quantity: 4,
    description:
      "Provence's most famous luxury rosé, from single centenarian Grenache vines — barrel-fermented and profound.",
    score: 93,
    appellation: "Côtes de Provence",
    price: 90,
    alcoholicStrength: 13.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Provence",
    address: "Route de Callian, 83920 La Motte, France",
    tastingNotes: "White peach, wild strawberry and vanilla; creamy texture, saline finish.",
    readyToDrink: true,
  },
  {
    id: "fr-ott-romassan-2023",
    name: "Château Romassan Bandol Rosé",
    producer: "Domaines Ott*",
    type: "rosé",
    grapeVariety: ["Mourvèdre", "Cinsault", "Grenache"],
    year: 2023,
    quantity: 5,
    description:
      "Organic rosé from Domaines Ott's Bandol estate, where limestone hills give Mourvèdre its backbone.",
    score: 92,
    appellation: "Bandol",
    price: 40,
    alcoholicStrength: 13.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Provence",
    address: "Route de Brégançon, 83250 La Londe-les-Maures, France",
    tastingNotes:
      "Blood orange, red currant and garrigue; structured and gastronomic with real persistence.",
    readyToDrink: true,
  },
  {
    id: "us-wolffer-estate-rose-2023",
    name: "Estate Rosé",
    producer: "Wölffer Estate Vineyards",
    type: "rosé",
    grapeVariety: ["Merlot", "Cabernet Franc", "Chardonnay"],
    year: 2023,
    quantity: 6,
    description:
      "The rosé that started it all — Long Island's Hamptons icon, complex with understated elegance.",
    score: 89,
    appellation: "The Hamptons, Long Island",
    price: 22,
    alcoholicStrength: 13.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "USA",
    region: "New York",
    address: "139 Sagg Road, Sagaponack, NY 11962, USA",
    tastingNotes: "Pink grapefruit, white peach and rose petal; crisp, dry and polished.",
    readyToDrink: true,
  },

  // ---------- Italy ----------
  {
    id: "it-barolo-2018",
    name: "Barolo Cannubi",
    producer: "Luciano Sandrone",
    type: "red",
    grapeVariety: ["Nebbiolo"],
    year: 2018,
    quantity: 2,
    description:
      "Powerful, perfumed Barolo from the fabled Cannubi cru.",
    score: 95,
    appellation: "Barolo",
    price: 95,
    alcoholicStrength: 14.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Italy",
    region: "Piedmont",
    address: "12060 Barolo, Italy",
    tastingNotes: "Tar, rose and red cherry; formidable tannins, long life ahead.",
    readyToDrink: false,
  },
  {
    id: "it-conterno-monfortino-2016",
    name: "Barolo Monfortino Riserva",
    producer: "Giacomo Conterno",
    type: "red",
    grapeVariety: ["Nebbiolo"],
    year: 2016,
    quantity: 1,
    description:
      "Italy's most mythical wine — decades in large Slavonian oak, released only in the finest years.",
    score: 99,
    appellation: "Barolo",
    price: 450,
    alcoholicStrength: 14.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Italy",
    region: "Piedmont",
    address: "Via del Castello, 12065 Monforte d'Alba, Italy",
    tastingNotes: "Dried rose, tar, camphor and dark cherry; immortal structure, endless finish.",
    readyToDrink: false,
  },
  {
    id: "it-brunello-2016",
    name: "Brunello di Montalcino",
    producer: "Biondi-Santi",
    type: "red",
    grapeVariety: ["Sangiovese"],
    year: 2016,
    quantity: 2,
    description:
      "Historic, age-worthy Brunello from the estate that defined it.",
    score: 97,
    appellation: "Brunello di Montalcino",
    price: 210,
    alcoholicStrength: 14.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Italy",
    region: "Tuscany",
    address: "53024 Montalcino, Italy",
    tastingNotes: "Dried cherry, leather and earth; majestic structure.",
    readyToDrink: false,
  },
  {
    id: "it-masseto-2018",
    name: "Masseto",
    producer: "Tenuta dell'Ornellaia",
    type: "red",
    grapeVariety: ["Merlot"],
    year: 2018,
    quantity: 2,
    description:
      "Italy's legendary 100% Merlot from Bolgheri's blue-clay amphitheatre — velvet and power.",
    score: 96,
    appellation: "Toscana IGT",
    price: 400,
    alcoholicStrength: 14.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Italy",
    region: "Tuscany",
    address: "Loc. Masseto, 57022 Bolgheri, Italy",
    tastingNotes: "Blackberry liqueur, mocha and sweet spices; opulent, seamless and deep.",
    readyToDrink: false,
  },

  // ---------- Spain ----------
  {
    id: "es-vegasicilia-2012",
    name: "Único",
    producer: "Vega Sicilia",
    type: "red",
    grapeVariety: ["Tempranillo", "Cabernet Sauvignon"],
    year: 2012,
    quantity: 1,
    description:
      "Spain's most revered red — monumental, slow-aged and rare.",
    score: 96,
    appellation: "Ribera del Duero",
    price: 260,
    alcoholicStrength: 14.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Spain",
    region: "Castilla y León",
    address: "47300 Peñafiel, Spain",
    tastingNotes: "Cedar, blackberry and tobacco; impossibly deep and long.",
    readyToDrink: false,
  },
  {
    id: "es-pingus-2019",
    name: "Pingus",
    producer: "Dominio de Pingus",
    type: "red",
    grapeVariety: ["Tinto Fino (Tempranillo)"],
    year: 2019,
    quantity: 1,
    description:
      "Peter Sisseck's cult Ribera del Duero — Spain's most sought-after modern red.",
    score: 97,
    appellation: "Ribera del Duero",
    price: 800,
    alcoholicStrength: 14.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Spain",
    region: "Castilla y León",
    address: "47340 Quintanilla de Onésimo, Spain",
    tastingNotes: "Blueberry, graphite and incense; dense yet weightless with grave-like minerality.",
    readyToDrink: false,
  },
  {
    id: "es-rioja-904-2010",
    name: "Gran Reserva 904",
    producer: "La Rioja Alta",
    type: "red",
    grapeVariety: ["Tempranillo"],
    year: 2010,
    quantity: 4,
    description:
      "Classic, oak-aged Rioja with real maturity in bottle.",
    score: 95,
    appellation: "Rioja",
    price: 72,
    alcoholicStrength: 13.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Spain",
    region: "La Rioja",
    address: "26200 Haro, Spain",
    tastingNotes: "Dried strawberry, vanilla and leather; silky and resolved.",
    readyToDrink: true,
  },

  // ---------- Portugal · Port & Fortified ----------
  {
    id: "pt-noval-nacional-2011",
    name: "Nacional Vintage Port",
    producer: "Quinta do Noval",
    type: "fortified",
    grapeVariety: ["Touriga Nacional", "Touriga Franca", "Tinta Roriz"],
    year: 2011,
    quantity: 1,
    description:
      "From ungrafted vines planted directly on Douro schist — declared only in exceptional years, the stuff of legend.",
    score: 100,
    appellation: "Douro",
    price: 650,
    alcoholicStrength: 20.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Portugal",
    region: "Douro",
    address: "4415-175 Vila Nova de Gaia, Portugal",
    tastingNotes:
      "Wondrous symmetry, perfect acidity and immense purity — surely the finest Nacional since the ethereal 1963.",
    readyToDrink: false,
  },
  {
    id: "pt-taylor-2017",
    name: "Vintage Port",
    producer: "Taylor Fladgate",
    type: "fortified",
    grapeVariety: ["Touriga Nacional"],
    year: 2017,
    quantity: 2,
    description:
      "Declared vintage Port built for decades of cellaring.",
    score: 98,
    appellation: "Douro",
    price: 90,
    alcoholicStrength: 20.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Portugal",
    region: "Douro",
    address: "4430-809 Vila Nova de Gaia, Portugal",
    tastingNotes: "Blackberry, liquorice and violet; monumental, tannic, sweet.",
    readyToDrink: false,
  },
  {
    id: "pt-grahams-2017",
    name: "Vintage Port",
    producer: "Graham's",
    type: "fortified",
    grapeVariety: ["Touriga Nacional", "Touriga Franca", "Tinta Barroca"],
    year: 2017,
    quantity: 3,
    description:
      "A classic declaration from the Symington family's storied Port house — dense, structured and long-lived.",
    score: 96,
    appellation: "Douro",
    price: 80,
    alcoholicStrength: 19.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Portugal",
    region: "Douro",
    address: "4400-111 Vila Nova de Gaia, Portugal",
    tastingNotes: "Black plum, cassis and dark chocolate; muscular spine, sweet persistent fruit.",
    readyToDrink: false,
  },
  {
    id: "pt-niepoort-colheita-2007",
    name: "Colheita",
    producer: "Niepoort",
    type: "fortified",
    grapeVariety: ["Touriga Nacional", "Tinta Roriz", "Tinta Amarela"],
    year: 2007,
    quantity: 4,
    description:
      "Single-vintage Tawny aged over a decade in old wood — Dirk Niepoort's elegant, oxidative style.",
    score: 92,
    appellation: "Douro",
    price: 45,
    alcoholicStrength: 19.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Portugal",
    region: "Douro",
    address: "Rua de Ceta 15, 4400-049 Vila Nova de Gaia, Portugal",
    tastingNotes: "Toffee, dried fig and roasted nuts; mellow, delicate and gently spiced.",
    readyToDrink: true,
  },
  {
    id: "es-sherry-lustau",
    name: "Amontillado",
    producer: "Emilio Lustau",
    type: "fortified",
    grapeVariety: ["Palomino"],
    year: 2015,
    quantity: 4,
    description:
      "Dry, nutty Sherry aged under solera in Jerez.",
    score: 92,
    appellation: "Jerez-Xeres",
    price: 19,
    alcoholicStrength: 18.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Spain",
    region: "Andalusia",
    address: "11402 Jerez de la Frontera, Spain",
    tastingNotes: "Walnut, caramel and dried orange; bone dry and complex.",
    readyToDrink: true,
  },

  // ---------- Uruguay ----------
  {
    id: "uy-bouza-tannat-2023",
    name: "Tannat",
    producer: "Bodega Bouza",
    type: "red",
    grapeVariety: ["Tannat"],
    year: 2023,
    quantity: 6,
    description:
      "Uruguay's signature grape from estate vineyards in Las Violetas, Canelón Chico and Melilla — 11 months in French and American oak.",
    score: 89,
    appellation: "Montevideo",
    price: 30,
    alcoholicStrength: 13.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Uruguay",
    region: "Canelones",
    address: "Camino de la Redención 7658, Montevideo, Uruguay",
    tastingNotes:
      "Mulberries, cassis and raisin over an elegant smoky background; firm yet velvety tannins.",
    readyToDrink: true,
  },
  {
    id: "uy-bouza-albarino-2024",
    name: "Albariño",
    producer: "Bodega Bouza",
    type: "white",
    grapeVariety: ["Albariño"],
    year: 2024,
    quantity: 6,
    description:
      "From the pioneers of Albariño in Uruguay — one of the country's most distinctive whites (17 points, JancisRobinson.com).",
    score: 90,
    appellation: "Montevideo",
    price: 27,
    alcoholicStrength: 13.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Uruguay",
    region: "Canelones",
    address: "Camino de la Redención 7658, Montevideo, Uruguay",
    tastingNotes:
      "Peach and white flowers; mouth-watering balance, broad texture and a long finish.",
    readyToDrink: true,
  },
  {
    id: "uy-bouza-parcelaunica-2020",
    name: "Parcela Única Tannat",
    producer: "Bodega Bouza",
    type: "red",
    grapeVariety: ["Tannat"],
    year: 2020,
    quantity: 3,
    description:
      "Single-parcel Tannat from Bouza's top selection — their flagship expression of Uruguay's national grape.",
    score: 92,
    appellation: "Montevideo",
    price: 55,
    alcoholicStrength: 14.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Uruguay",
    region: "Canelones",
    address: "Camino de la Redención 7658, Montevideo, Uruguay",
    tastingNotes: "Blackberry, violets and cocoa; concentrated yet fresh with fine-grained tannins.",
    readyToDrink: true,
  },

  // ---------- Australia ----------
  {
    id: "au-standish-relic-2020",
    name: "The Relic",
    producer: "The Standish Wine Company",
    type: "red",
    grapeVariety: ["Shiraz", "Viognier"],
    year: 2020,
    quantity: 2,
    description:
      "98% Shiraz with a whisper of Viognier from the Hongell Family Vineyard in Krondorf — Côte-Rôtie-inspired Barossa.",
    score: 96,
    appellation: "Barossa Valley",
    price: 110,
    alcoholicStrength: 14.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Australia",
    region: "South Australia",
    address: "319 Kalimna Road, Light Pass, SA 5355, Australia",
    tastingNotes: "Blueberry, apricot kernel and cracked pepper; plush, floral and long.",
    readyToDrink: false,
  },
  {
    id: "au-standish-thestandish-2020",
    name: "The Standish",
    producer: "The Standish Wine Company",
    type: "red",
    grapeVariety: ["Shiraz"],
    year: 2020,
    quantity: 2,
    description:
      "100% Shiraz from the Laycock Family Vineyard in Greenock — the eponymous flagship of the range.",
    score: 97,
    appellation: "Barossa Valley",
    price: 130,
    alcoholicStrength: 14.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Australia",
    region: "South Australia",
    address: "319 Kalimna Road, Light Pass, SA 5355, Australia",
    tastingNotes: "Ironstone, black fruits and liquorice; immense yet composed, very long.",
    readyToDrink: false,
  },
  {
    id: "au-standish-schuberttheorem-2021",
    name: "The Schubert Theorem",
    producer: "The Standish Wine Company",
    type: "red",
    grapeVariety: ["Shiraz"],
    year: 2021,
    quantity: 3,
    description:
      "100% Shiraz from Roennfeldt Road, Marananga — one of the Barossa's most revered patches of dirt.",
    score: 96,
    appellation: "Barossa Valley",
    price: 100,
    alcoholicStrength: 14.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Australia",
    region: "South Australia",
    address: "319 Kalimna Road, Light Pass, SA 5355, Australia",
    tastingNotes: "Dark plum, graphite and sage; dense, mineral-framed and finely wound.",
    readyToDrink: false,
  },
  {
    id: "au-standish-lamella-2021",
    name: "Lamella",
    producer: "The Standish Wine Company",
    type: "red",
    grapeVariety: ["Shiraz"],
    year: 2021,
    quantity: 3,
    description:
      "100% Shiraz from the Stonegarden Vineyard in the Eden Valley — 160-year-old vines on schist.",
    score: 95,
    appellation: "Eden Valley",
    price: 85,
    alcoholicStrength: 14.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Australia",
    region: "South Australia",
    address: "319 Kalimna Road, Light Pass, SA 5355, Australia",
    tastingNotes: "Red and black berries, blood orange and slate; cool-climate energy, savory close.",
    readyToDrink: false,
  },
  {
    id: "au-torbreck-laird-2021",
    name: "The Laird",
    producer: "Torbreck Vintners",
    type: "red",
    grapeVariety: ["Shiraz"],
    year: 2021,
    quantity: 1,
    description:
      "From a five-acre south-facing vineyard planted in 1958 between Seppeltsfield and Marananga — extraordinary power and restraint.",
    score: 98,
    appellation: "Barossa Valley",
    price: 450,
    alcoholicStrength: 14.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Australia",
    region: "South Australia",
    address: "Marananga, Barossa Valley SA 5355, Australia",
    tastingNotes:
      "Dense, complex and alluring; small-berry concentration that can be cellared for decades.",
    readyToDrink: false,
  },
  {
    id: "au-torbreck-runrig-2023",
    name: "RunRig",
    producer: "Torbreck Vintners",
    type: "red",
    grapeVariety: ["Shiraz", "Viognier"],
    year: 2023,
    quantity: 2,
    description:
      "Torbreck's icon from ancient dry-grown Shiraz vineyards, lifted by a splash of Viognier.",
    score: 96,
    appellation: "Barossa Valley",
    price: 175,
    alcoholicStrength: 14.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Australia",
    region: "South Australia",
    address: "Marananga, Barossa Valley SA 5355, Australia",
    tastingNotes: "Black raspberry, apricot and wild herbs; opulent texture, savory length.",
    readyToDrink: false,
  },
  {
    id: "au-henschke-hillofgrace-2018",
    name: "Hill of Grace",
    producer: "Henschke",
    type: "red",
    grapeVariety: ["Shiraz"],
    year: 2018,
    quantity: 1,
    description:
      "From vines planted around 1860 beside a Lutheran church in the Eden Valley — one of Australia's two holy grails.",
    score: 98,
    appellation: "Eden Valley",
    price: 550,
    alcoholicStrength: 14.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Australia",
    region: "South Australia",
    address: "Keyneton SA 5353, Australia",
    tastingNotes: "Blackberry, anise and earth; silken, profound and hauntingly beautiful.",
    readyToDrink: false,
  },
  {
    id: "au-penfolds-grange-2018",
    name: "Grange",
    producer: "Penfolds",
    type: "red",
    grapeVariety: ["Shiraz", "Cabernet Sauvignon"],
    year: 2018,
    quantity: 2,
    description:
      "Australia's most famous wine — multiregional Shiraz of extraordinary concentration and longevity.",
    score: 97,
    appellation: "South Australia",
    price: 500,
    alcoholicStrength: 14.5,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Australia",
    region: "South Australia",
    address: "78 Penfold Road, Magill SA 5072, Australia",
    tastingNotes: "Black forest fruits, espresso and licorice; massive yet impeccably balanced.",
    readyToDrink: false,
  },

  // ---------- USA ----------
  {
    id: "us-screamingeagle-2018",
    name: "Screaming Eagle",
    producer: "Screaming Eagle",
    type: "red",
    grapeVariety: ["Cabernet Sauvignon"],
    year: 2018,
    quantity: 1,
    description:
      "Cult Napa Cabernet — tiny production, colossal demand.",
    score: 99,
    appellation: "Napa Valley",
    price: 3200,
    alcoholicStrength: 14.8,
    bottleVolume: 750,
    containsSulphites: true,
    country: "USA",
    region: "California",
    address: "94558 Oakville, California, USA",
    tastingNotes: "Crème de cassis, mocha and violets; impossibly rich yet balanced.",
    readyToDrink: false,
  },
  {
    id: "us-kistler-2019",
    name: "Sonoma Coast Pinot Noir",
    producer: "Kistler Vineyards",
    type: "red",
    grapeVariety: ["Pinot Noir"],
    year: 2019,
    quantity: 3,
    description:
      "Silky, site-driven Sonoma Pinot from a cult producer.",
    score: 94,
    appellation: "Sonoma Coast",
    price: 80,
    alcoholicStrength: 14.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "USA",
    region: "California",
    address: "95472 Sonoma, California, USA",
    tastingNotes: "Red cherry, forest floor and spice; silky and long.",
    readyToDrink: true,
  },

  // ---------- Argentina & Chile ----------
  {
    id: "ar-nicolas-2018",
    name: "Nicolás Catena Zapata",
    producer: "Catena Zapata",
    type: "red",
    grapeVariety: ["Malbec", "Cabernet Sauvignon"],
    year: 2018,
    quantity: 3,
    description:
      "Argentina's first world-class Bordeaux-blend Malbec.",
    score: 95,
    appellation: "Mendoza",
    price: 80,
    alcoholicStrength: 14.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Argentina",
    region: "Mendoza",
    address: "5505 Luján de Cuyo, Mendoza, Argentina",
    tastingNotes: "Blackberry, violet and graphite; structured and ageworthy.",
    readyToDrink: true,
  },
  {
    id: "ar-piedrainfinita-2019",
    name: "Finca Piedra Infinita",
    producer: "Zuccardi",
    type: "red",
    grapeVariety: ["Malbec"],
    year: 2019,
    quantity: 2,
    description:
      "Single-vineyard Malbec from Paraje Altamira, high altitude.",
    score: 96,
    appellation: "Paraje Altamira",
    price: 60,
    alcoholicStrength: 14.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "Argentina",
    region: "Mendoza",
    address: "5565 San Carlos, Mendoza, Argentina",
    tastingNotes: "Blue fruit, chalk and herbs; precise and mineral.",
    readyToDrink: true,
  },

  // ---------- Dessert ----------
  {
    id: "fr-yquem-2017",
    name: "Château d'Yquem",
    producer: "Château d'Yquem",
    type: "dessert",
    grapeVariety: ["Sémillon", "Sauvignon Blanc"],
    year: 2017,
    quantity: 1,
    description:
      "The legendary Sauternes — opulent, honeyed and near-immortal.",
    score: 97,
    appellation: "Sauternes",
    price: 320,
    alcoholicStrength: 14.0,
    bottleVolume: 750,
    containsSulphites: true,
    country: "France",
    region: "Bordeaux",
    address: "33210 Sauternes, France",
    tastingNotes: "Apricot, saffron and candied citrus; luscious yet precise.",
    readyToDrink: true,
  },
  {
    id: "hu-royaltokaji-aszu-2016",
    name: "The Royal Tokaji Aszú 5 Puttonyos",
    producer: "Royal Tokaji Wine Company",
    type: "dessert",
    grapeVariety: ["Furmint", "Hárslevelű"],
    year: 2016,
    quantity: 4,
    description:
      "Botrytis dessert wine from Hungary's historic Tokaj region — the original 'wine of kings'.",
    score: 92,
    appellation: "Tokaji Aszú",
    price: 35,
    alcoholicStrength: 11.0,
    bottleVolume: 500,
    containsSulphites: true,
    country: "Hungary",
    region: "Tokaj",
    address: "Mád, 3915 Hungary",
    tastingNotes: "Orange peel, honey and saffron; sweet yet fiery with volcanic acidity.",
    readyToDrink: true,
  },
];
